name: Lint with Ruff
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: pip
      - run: pip install ruff
      - run: |
          ruff check . --output-format=github
          ruff format --check .
    timeout-minutes: 5
