name: Lint with Ruff
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Run the Ruff Linter
        uses: astral-sh/ruff-action@v4.1.0
      - name: Run the Ruff Formatter
        run: ruff format --check .
    timeout-minutes: 5
